title: Pergande Lab
subtitle: Boston University
description: Chemical biology and mass spectrometry-based target discovery at Boston University.
header:
footer:
proofer: false
url: https://wgazlay1.github.io
baseurl: /lab-website-v2

links:
  email: contact@your-lab.com
  github: wgazlay1

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true
  posts:
    output: true

plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

highlighter: rouge

theme: null

sass:
  sass_dir: _styles

include:
  - _styles
  - _scripts

exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
